# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Esencial\Doc\Corte3\IAProyecto3\view\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.General = QtWidgets.QWidget(self.centralwidget)
        self.General.setObjectName("General")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.General)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Imagen = QtWidgets.QVBoxLayout()
        self.Imagen.setObjectName("Imagen")
        self.horizontalLayout_2.addLayout(self.Imagen)
        self.prediccion = QtWidgets.QLabel(self.General)
        self.prediccion.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 170, 0);")
        self.prediccion.setText("")
        self.prediccion.setAlignment(QtCore.Qt.AlignCenter)
        self.prediccion.setObjectName("prediccion")
        self.horizontalLayout_2.addWidget(self.prediccion)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineRuta = QtWidgets.QLineEdit(self.General)
        self.lineRuta.setObjectName("lineRuta")
        self.horizontalLayout.addWidget(self.lineRuta)
        self.buttonAbrir = QtWidgets.QPushButton(self.General)
        self.buttonAbrir.setObjectName("buttonAbrir")
        self.horizontalLayout.addWidget(self.buttonAbrir)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonPredictNuevo = QtWidgets.QPushButton(self.General)
        self.buttonPredictNuevo.setObjectName("buttonPredictNuevo")
        self.horizontalLayout_4.addWidget(self.buttonPredictNuevo)
        self.buttonpredictGuardado = QtWidgets.QPushButton(self.General)
        self.buttonpredictGuardado.setObjectName("buttonpredictGuardado")
        self.horizontalLayout_4.addWidget(self.buttonpredictGuardado)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.General, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonAbrir.setText(_translate("MainWindow", "Abrir"))
        self.buttonPredictNuevo.setText(_translate("MainWindow", "Prediccion Entrenamiento Nuevo"))
        self.buttonpredictGuardado.setText(_translate("MainWindow", "Prediccion Entrenamiento Guardado"))
